[package]
name = "ceres-macros"
version = "0.0.5"
edition = "2021"
description = "Procedural macros for the ceres-dsp framework"
license = "MIT OR Apache-2.0"
repository = "https://github.com/MoofSoup/ceres-dsp"
keywords = ["dsp", "macros", "proc-macro"]
categories = ["development-tools::procedural-macro-helpers"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }